{"name": "Тест перехода на страницу восстановления пароля", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=128.0.6613.138)\nStacktrace:\n0   chromedriver                        0x00000001032c1208 cxxbridge1$str$ptr + 1927396\n1   chromedriver                        0x00000001032b966c cxxbridge1$str$ptr + 1895752\n2   chromedriver                        0x0000000102eb4808 cxxbridge1$string$len + 89564\n3   chromedriver                        0x0000000102e8fb0c core::str::slice_error_fail::h6c488016ada29016 + 3776\n4   chromedriver                        0x0000000102f1f4d8 cxxbridge1$string$len + 527020\n5   chromedriver                        0x0000000102f31c90 cxxbridge1$string$len + 602724\n6   chromedriver                        0x0000000102eed698 cxxbridge1$string$len + 322668\n7   chromedriver                        0x0000000102eee310 cxxbridge1$string$len + 325860\n8   chromedriver                        0x0000000103287e78 cxxbridge1$str$ptr + 1693012\n9   chromedriver                        0x000000010328c77c cxxbridge1$str$ptr + 1711704\n10  chromedriver                        0x000000010326d3ec cxxbridge1$str$ptr + 1583816\n11  chromedriver                        0x000000010328d04c cxxbridge1$str$ptr + 1713960\n12  chromedriver                        0x000000010325dfc8 cxxbridge1$str$ptr + 1521316\n13  chromedriver                        0x00000001032aab68 cxxbridge1$str$ptr + 1835588\n14  chromedriver                        0x00000001032aace4 cxxbridge1$str$ptr + 1835968\n15  chromedriver                        0x00000001032b9308 cxxbridge1$str$ptr + 1894884\n16  libsystem_pthread.dylib             0x000000018b8af2e4 _pthread_start + 136\n17  libsystem_pthread.dylib             0x000000018b8aa0fc thread_start + 8", "trace": "self = <tests.test_password_recovery.TestPasswordRecovery object at 0x10418fa70>\n\n    @allure.title(\"Тест перехода на страницу восстановления пароля\")\n    @pytest.mark.usefixtures(\"driver\")\n    def test_page_password_recovery(self):\n        self.driver.get(main_url)\n        client = PagePasswordRecovery(self.driver)\n>       client.check_password_recovery_page()\n\ntests/test_password_recovery.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/page_password_recovery.py:24: in check_password_recovery_page\n    self.click_virt_mouse(self.button_sign_in)\npages/base_page.py:50: in click_virt_mouse\n    WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(element))\nvenv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:96: in until\n    value = method(self._driver)\nvenv/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py:363: in _predicate\n    target = driver.find_element(*target)  # grab element at locator\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:748: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x1042f0da0>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such window\",\"message\":\"no such window: target window already closed\\\\...00018b8af2e4 _pthread_start + 136\\\\n17  libsystem_pthread.dylib             0x000000018b8aa0fc thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nE       from unknown error: web view not found\nE         (Session info: chrome=128.0.6613.138)\nE       Stacktrace:\nE       0   chromedriver                        0x00000001032c1208 cxxbridge1$str$ptr + 1927396\nE       1   chromedriver                        0x00000001032b966c cxxbridge1$str$ptr + 1895752\nE       2   chromedriver                        0x0000000102eb4808 cxxbridge1$string$len + 89564\nE       3   chromedriver                        0x0000000102e8fb0c core::str::slice_error_fail::h6c488016ada29016 + 3776\nE       4   chromedriver                        0x0000000102f1f4d8 cxxbridge1$string$len + 527020\nE       5   chromedriver                        0x0000000102f31c90 cxxbridge1$string$len + 602724\nE       6   chromedriver                        0x0000000102eed698 cxxbridge1$string$len + 322668\nE       7   chromedriver                        0x0000000102eee310 cxxbridge1$string$len + 325860\nE       8   chromedriver                        0x0000000103287e78 cxxbridge1$str$ptr + 1693012\nE       9   chromedriver                        0x000000010328c77c cxxbridge1$str$ptr + 1711704\nE       10  chromedriver                        0x000000010326d3ec cxxbridge1$str$ptr + 1583816\nE       11  chromedriver                        0x000000010328d04c cxxbridge1$str$ptr + 1713960\nE       12  chromedriver                        0x000000010325dfc8 cxxbridge1$str$ptr + 1521316\nE       13  chromedriver                        0x00000001032aab68 cxxbridge1$str$ptr + 1835588\nE       14  chromedriver                        0x00000001032aace4 cxxbridge1$str$ptr + 1835968\nE       15  chromedriver                        0x00000001032b9308 cxxbridge1$str$ptr + 1894884\nE       16  libsystem_pthread.dylib             0x000000018b8af2e4 _pthread_start + 136\nE       17  libsystem_pthread.dylib             0x000000018b8aa0fc thread_start + 8\n\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchWindowException"}, "steps": [{"name": "Проверка перехода на странице восстановления пароля", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=128.0.6613.138)\nStacktrace:\n0   chromedriver                        0x00000001032c1208 cxxbridge1$str$ptr + 1927396\n1   chromedriver                        0x00000001032b966c cxxbridge1$str$ptr + 1895752\n2   chromedriver                        0x0000000102eb4808 cxxbridge1$string$len + 89564\n3   chromedriver                        0x0000000102e8fb0c core::str::slice_error_fail::h6c488016ada29016 + 3776\n4   chromedriver                        0x0000000102f1f4d8 cxxbridge1$string$len + 527020\n5   chromedriver                        0x0000000102f31c90 cxxbridge1$string$len + 602724\n6   chromedriver                        0x0000000102eed698 cxxbridge1$string$len + 322668\n7   chromedriver                        0x0000000102eee310 cxxbridge1$string$len + 325860\n8   chromedriver                        0x0000000103287e78 cxxbridge1$str$ptr + 1693012\n9   chromedriver                        0x000000010328c77c cxxbridge1$str$ptr + 1711704\n10  chromedriver                        0x000000010326d3ec cxxbridge1$str$ptr + 1583816\n11  chromedriver                        0x000000010328d04c cxxbridge1$str$ptr + 1713960\n12  chromedriver                        0x000000010325dfc8 cxxbridge1$str$ptr + 1521316\n13  chromedriver                        0x00000001032aab68 cxxbridge1$str$ptr + 1835588\n14  chromedriver                        0x00000001032aace4 cxxbridge1$str$ptr + 1835968\n15  chromedriver                        0x00000001032b9308 cxxbridge1$str$ptr + 1894884\n16  libsystem_pthread.dylib             0x000000018b8af2e4 _pthread_start + 136\n17  libsystem_pthread.dylib             0x000000018b8aa0fc thread_start + 8\n\n", "trace": "  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/pages/page_password_recovery.py\", line 24, in check_password_recovery_page\n    self.click_virt_mouse(self.button_sign_in)\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/pages/base_page.py\", line 50, in click_virt_mouse\n    WebDriverWait(self.driver, 5).until(EC.element_to_be_clickable(element))\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/venv/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py\", line 363, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/ulabualskaa/Documents/GitHub/Diplom_3/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1727003943778, "stop": 1727003943779}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1727003942811, "stop": 1727003943780, "uuid": "daf48259-15d8-4d51-b1bf-8b2ac647d3ad", "historyId": "03d6b0bf9659b872a1cdb0a1b5c391b6", "testCaseId": "1b370fa5f6922bddca69e85a184bfe6c", "fullName": "tests.test_password_recovery.TestPasswordRecovery#test_page_password_recovery", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_password_recovery"}, {"name": "subSuite", "value": "TestPasswordRecovery"}, {"name": "host", "value": "MacBook-Pro-Ula.local"}, {"name": "thread", "value": "8096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_password_recovery"}]}